<?php

namespace EducationBundle\Repository;

/**
 * conteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class conteRepository extends \Doctrine\ORM\EntityRepository
{


}
