<?php

namespace EducationBundle\Repository;

/**
 * GarderieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GarderieRepository extends \Doctrine\ORM\EntityRepository
{

    public function findTrierDQL()
    {
        $query=$this->getEntityManager()->createQuery("SELECT m from EducationBundle:Garderie m ORDER BY m.rating DESC ");
        return $query->getResult();
        var_dump($query);
}

}
