<?php

namespace EducationBundle\Repository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends \Doctrine\ORM\EntityRepository
{

    public function findtestconte($p)
{

    $query=$this->getEntityManager()->createQuery
    (
        "select m from EducationBundle:test m WHERE m.conte=:p"
    )->setParameter('p','%'.$p.'%');
    return $query->getResult();
}
    public function findtestenfant($p)
    {

        $query=$this->getEntityManager()->createQuery
        (
            "select m from EducationBundle:test m WHERE m.enfant=:p"
        )->setParameter('p','%'.$p.'%');
        return $query->getResult();
    }

}
