<?php

namespace gestionsanteBundle\Repository;

/**
 * PediatreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PediatreRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTrierDQL()
    {
        $query=$this->getEntityManager()->createQuery("SELECT m FROM gestionsanteBundle:Pediatre m ORDER BY m.rating DESC ");
        return $query->getResult();
    }
}
