<?php

namespace BoutiqueBundle\Repository;

/**
 * BoutiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoutiqueRepository extends \Doctrine\ORM\EntityRepository
{

    public function GetBestShopsDQL()
    {
        $query=$this->getEntityManager()->createQuery("select b from BoutiqueBundle:Boutique b WHERE b.totalachat >220");
        return $query->getResult();
    }

    public function GetSellsDQL()
    {
        $query=$this->getEntityManager()->createQuery("select b.totalachat from BoutiqueBundle:Boutique b");
        return $query->getResult();
    }
}
