<?php

namespace BoutiqueBundle\Repository;

/**
 * PanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanierRepository extends \Doctrine\ORM\EntityRepository
{
    public function findExistant($id, $userId){
        $query = $this->getEntityManager()
            ->createQuery("select i from BoutiqueBundle:Panier i WHERE (i.produitId=:id) AND (i.userId=:userId)")
            ->setParameters(array('id'=> $id, 'userId' => $userId)); //très important! parameterS
        return $query->getResult();
    }

    public function findUserCart($userId)
    {
        $query = $this->getEntityManager()
            ->createQuery("select i.id from BoutiqueBundle:Panier i WHERE (i.userId=:userId)")
            ->setParameter('userId',$userId); //très important! parameterS
        return $query->getResult();
    }


        public function LastIdCart()
    {
        $query = $this->getEntityManager()
            ->createQuery("select i.id from BoutiqueBundle:Panier i ORDER BY i.id DESC LIMIT 1");
        return $query->getResult();
    }

    public function TotalAchatUser($userId)
    {
        $query = $this->getEntityManager()
            ->createQuery("select count (i.userId) from BoutiqueBundle:Panier i WHERE (i.userId=:userId)")
            ->setParameter('userId',$userId); //très important! parameterS
        return $query->getResult();
    }
}
